// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4, iterations: "10" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseApi: "http://localhost:64773/api/"
  }
});

export default function() {
  postman[Request]({
    name: "RADIX SENSOR INPUT",
    id: "4f594fba-656f-41cb-b560-6956da3f1790",
    method: "POST",
    //address: "{{baseApi}}sensor",
    address: "http://localhost:64773/api/sensor",
    data:
	  '{\n   "timestamp": 1539112021301,\n   "tag": "brasil.sudeste.sensor01",\n   "valor" : "27"\n}\n',
	headers: {
		"Content-Type": "applicatoin/json"
	},
    post(response) {
      pm.test(() => {
        var jsonData = pm.response.json();        
        pm.expect(jsonData.json).to.eql({          
          pais: "Pais teste",
          regiao: "Regiao teste",
          nome: "Nome Teste",
          valor: 123
        });
      });
    }
  });
}
